<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.pilog.mdm.cloud</groupId>
    <artifactId>iVisionDXP</artifactId>
    <version>1</version>
    <packaging>war</packaging>
    <name>iVisionDXP-1</name>
    <dependencies>
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>12.10.0.jre11</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPAnalyzer</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPCluster</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPAILens</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPDuplicateCheck</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPDropDown</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPSmartConsolidation</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPDeDuplication</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPTree</artifactId>
            <version>1</version>
        </dependency>
        <!-- osdt_core -->
        <dependency>
            <groupId>com.oracle.database.security</groupId>
            <artifactId>osdt_core</artifactId>
            <version>21.9.0.0</version>
        </dependency>

        <!-- osdt_cert -->
        <dependency>
            <groupId>com.oracle.database.security</groupId>
            <artifactId>osdt_cert</artifactId>
            <version>21.9.0.0</version>
        </dependency>

        <!-- oraclepki (in case you need to realign version) -->
        <dependency>
            <groupId>com.oracle.database.security</groupId>
            <artifactId>oraclepki</artifactId>
            <version>21.9.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPAnalyzer</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPSearch</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPWorkflow</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPMenu</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPPojos</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPConfig</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPLogin</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPGrid</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>com.pilog.mdm.cloud</groupId>
            <artifactId>iDXPBusinessLogic</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>iDXPDashboard</artifactId>
            <version>1.0</version>
        </dependency>
    </dependencies>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jakartaee>11.0.0-M1</jakartaee>
    </properties>      
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.12.1</version>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.4.0</version>
            </plugin>
            <plugin>
                <groupId>org.jboss.jandex</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
                <version>1.2.3</version>
                <executions>
                    <execution>
                        <id>make-index</id>
                        <goals>
                            <goal>jandex</goal>
                        </goals>
                        <!-- phase is 'process-classes by default' -->
                        <configuration>
                            <!-- Nothing needed here for simple cases -->
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>