#oracle
jdbc.driver=oracle.jdbc.OracleDriver
dataSouceClassName=oracle.jdbc.pool.OracleDataSource
hibernate.dialect=org.hibernate.dialect.OracleDialect
#IDXP 
jdbc.url=jdbc:oracle:thin:@//172.16.1.33:1521/PDBVISIONSSD
jdbc.username=DR1024231
jdbc.accessName=PDBVISIONSSD
jdbc.password=Pipl#mdrm$231

#MsSQL
#jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
#dataSouceClassName=com.microsoft.sqlserver.jdbc.SQLServerDataSource
#hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#jdbc.url=jdbc:sqlserver://172.16.1.108:1433;databaseName=pilogdb;encrypt=true;trustServerCertificate=true;
##jdbc.username=pilog_user1
##jdbc.password=YourStrongPassword@123
#jdbc.username=pilog
#jdbc.password=Pilog#123



#jdbc.url=jdbc:oracle:thin:@//172.16.1.33:1521/PDBVISIONSSD
#jdbc.username=DI1228024
#jdbc.accessName=PDBVISIONSSD
#jdbc.password=PipL_iDxp_24

#VARDHMAN
#jdbc.url=jdbc:oracle:thin:@//20.244.5.215:1521/DR101959
#jdbc.username=DR102959
#jdbc.accessName=DR101959
#jdbc.password=Pipl#mdrm_959

##VARDHMAN PROD
#jdbc.url=jdbc:oracle:thin:@//20.244.5.215:1521/DR101959
#jdbc.accessName=DR101959
#jdbc.username=DR102961
#jdbc.password=Pipl#mdrm_961

#NWC LOCAL
#jdbc.url=jdbc:oracle:thin:@//172.16.1.22:1521/IDXPDEVPDB
#jdbc.username=DI1228016
#jdbc.password=Pipl#iDxp_016


#jdbc.url=jdbc:oracle:thin:@//20.173.104.179:1521/DH111700
#jdbc.username=DH112701
#jdbc.password=Pipl#Dh_701


#IDXPLGInstance

#jdbc.url=jdbc:oracle:thin:@//172.16.1.13:1522/DR101411
#jdbc.username=DR1024241
#jdbc.password=Pipl#Mdrm_241


##KJO IDXP NEW
#jdbc.url=jdbc:oracle:thin:@//172.16.1.54:1521/DEVSAB
#jdbc.username=DR1024244
#jdbc.password=Pipl#iDxp_244

#QAFAC iDXP Azure Dev=
#jdbc.url=jdbc:oracle:thin:@//20.173.104.179:1521/DH111700
#jdbc.username= DH112701
#jdbc.password= Pipl#Dh_701

##VARDHAMAN
#jdbc.url=jdbc:oracle:thin:@//20.244.5.215:1521/DR101959
#jdbc.username=DR102959
#jdbc.password=Pipl#mdrm_959
#jdbc.accessName=DR101959

##KJO IDXP OCI
#jdbc.url=jdbc:oracle:thin:@//129.151.158.213:1521/ADACPDB.adacdb.adacdb.oraclevcn.com
#jdbc.username=DI1228011
#jdbc.password=Pipl#idxp_011


#JSIS IDXP OCI
#jdbc.url=jdbc:oracle:thin:@//129.151.143.76:1521/JSISDB_PDB1.jsisdbsubnet.jsisvcndb.oraclevcn.com
#jdbc.username=DI1228015
#jdbc.password=Pipl#iDxp_015

#JSIS NEW
#jdbc.url=jdbc:oracle:thin:@//74.243.217.246:1521/JSISPDB
#jdbc.username=DI1228015
#jdbc.password=Pipl#iDxp_015

##NWC_IDXP
#jdbc.url=jdbc:oracle:thin:@//172.16.1.22:1521/IDXPDEVPDB
#jdbc.username=DI1228016
#jdbc.password=Pipl#iDxp_016

##SPCC SPCCPDB_DEV 
#jdbc.url=jdbc:oracle:thin:@//193.122.93.110:1521/SPCCPDB.spccsubnetdb.spccvcndb.oraclevcn.com
#jdbc.username=DR1024245
#jdbc.password=Pipl#iDxp_245

#VARDHMAN
#jdbc.url=jdbc:oracle:thin:@//20.244.5.215:1521/DR101959
#jdbc.username=DR102959
#jdbc.accessName=DR101959
#jdbc.password=Pipl#mdrm_959

#Nuvaco Dev
#jdbc.url=jdbc:oracle:thin:@//172.16.20.108:1521/PILOGQAPDB
#jdbc.username=NUVOCO_IDXP_QA
#jdbc.accessName=PILOGQAPDB
#jdbc.password=NuV0(0_iDxp#2Q24


#-------------------

468788271FE5050EE053460AA9C06D4D=Y
#login.scroll.message=  NOTE : Please note, From 18-02-22 onwords the current URL will be changed to 'https://imdrm.pilogcloud.com'.
#
schedular.isScheduleRun=N
schedular.isScheduleDeliveryRun=N
schedular.isLicenceScheduleRun=N
schedular.isSessionScheduleRun=N
schedular.isRemainderMailScheduleRun=N
schedular.isAutoTransferToSAP=N
schedular.isAutoDeletionRecords=N
schedular.isPLMScheduleRun=N
schedular.isOpenTextSchedular=N
#CI  
schedular.isCIRFxScheduleRun=N
schedular.isMailSslTrust=Y
schedular.isXmlFileReaderRun=N
schedular.isScheduleExtRemainderMailNext7days=N

##
#schedular.isScheduleRun=Y
#schedular.isScheduleDeliveryRun=Y
#schedular.isLicenceScheduleRun=Y
#schedular.isSessionScheduleRun=Y
#schedular.isRemainderMailScheduleRun=Y
#schedular.isAutoTransferToSAP=Y

payment.razorpay.key=rzp_test_iZRlZZY0ryQPzv
payment.razorpay.key.secret=HsTtoUmmtl41gdPDRYs93pW5
google.api.key=AIzaSyBvj6X46mBnOlDk9FADbTIo5VH9cKxJmdU
hibernate.show_sql=false
hibernate.format_sql=false
#hibernate.hbm2ddl.auto=N
#hibernate.hbm2ddl.auto=update

hibernate.validator.apply_to_ddl=false
hibernate.validator.autoregister_listeners=false
hibernate.use_sql_comments=false
hibernate.generate_statistics=false
hibernate.connection.release_mode=after_transaction
hibernate.jdbc.batch_size=1000
hibernate.jdbc.fetch_size=500
MultipartResolver.fileUploadSize=2070596096
MultipartResolver.fileinMemorySize=2070596096
jdbc.batchSize=60000
show.SOP=Y
Application.DefaultLocale=en_US
Application.enable.SSO=Y
Application.disable.CSRF=N
Application.disable.CSP=N
#Application.enable.clientCSPFlag=N
Application.disable.LOGIN.LINKS=N
Application.SAML.idpXmlFilePath=E:\\NWCDEVSAML\\NWCMDRMDEVIDP.xml
Application.SAML.spXmlFilePath=E:\\NWCDEVSAML\\NWCMDRMDEVSP.xml
Application.SAML.sslCertFilePath=E:\\NWCDEVSAML\\nwc.com.sa.crt
Application.SAML.pKeyFilePath=E:\\NWCDEVSAML\\private_PKCS8.key
Application.SAML.nameIDPolicyFormat=urn:oasis:names:tc:SAML:2.0:nameid-format:emailAddress
# DB Connction  pooling Config
hibernate.pool.max_size=400
hibernate.pool.min_size=250
hibernate.pool.idle_test_period=6000
hibernate.pool.minimumIdle=1
hibernate.pool.ConnectionTimeout=300000

#Schedulars Configuration Starts

cronTriggerEmailExp=0 */1 * * * ?    
cronTriggerAutoDeletion=0 0 0 * * ?  
cronTriggerAutoTransferToERPExp=0 */1 * * * ?  
cronTriggerdomainAutoTransferToERPExp=0 */1 * * * ?  
cronTriggerSfdcReqProcess=0 */1 * * * ?
cronTriggerSfdcResponseSending=0 */1 * * * ? 
#cronTriggerEmailExp=0 */15 * * * ?
cronTriggerEmailDeliverStatusExp=0 */20 * * * ?
cronTriggerLicenceExp=0 00 10 ? * *
#cronTriggerRemainderMailExp=0 30 11 * * ? *
cronTriggerRemainderMailExp=0 */3 * * * ?
cronTriggerExpiryMailExp=0 */3 * * * ?
cronTriggerSessionExp=0 */1  * * * ?
cronTriggerAutoFileDeletion=0 */1  * * * ?
cronTriggerOutOfOffc=0 */1  * * * ?
cronTriggerAutoSyncTables=0 */1  * * * ?
cronTriggerAutoRefreshCharData=0 */1  * * * ?
cronTriggerMailReport=0 */1  * * * ?
cronTriggerPlmData=0 */1 * * * ?
cronTriggerOpenTextIntProcess=0 */1 * * * ?
cronTriggerXmlFileReader=0 */1 * * * ?
#CI    
cronTriggerCIRFxData=0 0 12 * * ?
cronTriggerExtRemainderMailNext7days=0 0 * * * ?

#For windows
file.storeFilePath=C:\\Files
file.storeDMSFilePath=D:\\DMSINTEGRATION
#For Linex
#file.storeFilePath =/home/oracle/JBOSS
#file.storeDMSFilePath =/home/oracle/JBOSS/DMSINTEGRATION
#hibernate.search.default.directory_provider=filesystem
#hibernate.search.default.indexBase=D:/VisionMassSearchIndex

hibernate.search.enabled=true
hibernate.search.backends.lucene.type=lucene
hibernate.search.backends.lucene.directory.type=local-filesystem
hibernate.search.backends.lucene.directory.root=D:/ZakMsSqlIndex
hibernate.search.backend.io.commit_interval=2000
hibernate.search.backend.io.refresh_interval=5000
hibernate.search.backend.lucene.writer.ram_buffer_size=256
hibernate.search.backend.lucene.writer.max_buffered_docs=1000
#Zak
#hibernate.search.backend.directory.root=D:/VisionMassSearchIndex
#hibernate.search.backend.type=filesystem
#zak
#Below parameters are used for optimizing index performance 
#Defragments index for every 1000 (insert, update) operations
#hibernate.search.default.optimizer.operation_limit.max = 1000
##Defragments index for every 100 transactions
#hibernate.search.default.optimizer.transaction_limit.max = 100
ALLOWED_HOSTS = idxp1.pilogcloud.com,localhost:8080,localhost:8081,localhost:8082,localhost:8083,localhost:8443,esaidxp.pilogcloud.com,qafac.pilogcloud.com,idxp2.pilogcloud.com,idxpgolden.pilogcloud.com,spcc.pilogcloud.com,old.pilogcloud.com,piloggroup.com, localhost:80, localhost:443, 172.16.1.15:443, 172.16.1.102:443,172.16.1.15,172.16.1.102,smartdev.integraldataanalytics.com,129.151.151.221,knowthepulse.intellisensesolutions.com,rac.pilogcloud.com,129.151.151.221:80,129.151.151.221:443,jsis.pilogcloud.com,apimobile.intellisensesolutions.com


#index.directory=C:/V10SearchIndex
#jndiname=jdbc/Vision_Demo
#jndiname=jdbc/VisionPROD
#jndiname=jdbc/WelspunPROD